### PR TITLE
Add monitoring namespace creation to Kustomization config

### PR DESCRIPTION
**Pull request by zizekuros**
Hi there! I found your repo and wanted to try it because I had trouble with Prometheus, Loki, & Promtail a few weeks ago. Your project could have really helped me speed up my work back then.

When I tried your setup, I saw right away that a namespace was missing. So, I added it to the kustomization config.

This is my first time trying to contribute to open source with this Pull Request. I hope you like it, and I'm excited about maybe working together more in the future. :)

### CODE REVIEW

**Comment by saidsef** [comment]
@zizekuros Welcome and thanks for contributing.

Typically this is deployed via GitOps such as ArgoCD and Flux as they create the namespace dynamically - implicitly.  Declaring the namespace explicitly will make things clearer.

I am happy for this commit to be merge. However, it appears there is a merge conflict.

Could you please rebase and fix the merge conflict?

**Comment by zizekuros** [comment]
Hi again, thanks for getting back!

I rebased it and resolved the conflict. Looks fine to me now, can you check it?

**Review by saidsef — APPROVED** [review]
Hi @zizekuros , looks good, happy for it to merge.

However, I will need to update the CI to remove pre-flight namespace creation.  This can be done after merge.

Again. Thanks for contributing.

**Comment by zizekuros** [comment]
Happy to see it got approved!

I'm not sure about your plans for this repository, but please feel free to assign me some work if you think there's something I can help with.

**Pull request merged**
